// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Returns the total number of users
	CountUsers(ctx context.Context) (int64, error)
	// Creates a new user record, returns created user
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Deletes a user by the key
	DeleteUser(ctx context.Context, id int32) error
	// Fetches a single user by key
	GetUserByID(ctx context.Context, id int32) (User, error)
	// Returns list of users ordered by ID
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Updates a user's name and dob, updated row.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
